= BIW2-09 Beleg

Dieses Repository trackt meinen Fortschritt bei diesem Beleg.

Momentan beinhaltet es alle Testdateien, sowie alles was nicht das Resultat eines Kompilierungsvorganges ist.

Um das Projekt zu kompilieren bedarf es folgender Befehlszeile

.Befehl für den gfortran compiler
[source,bash]
----
gfortran hilfsfunktionen.f90 Dreiecksform.f90 laplaceNaiv.f90 laplaceAbsuchen.f90 DreiecksformPivotisierung.f90 main.f90 -o Beleg.exe
----

Um die Performance zu testen muss folgendermaßen kompiliert werden

.Befehl für den gfortran compiler
[source,bash]
----
gfortran performance.f90 hilfsfunktionen.f90 Dreiecksform.f90 laplaceNaiv.f90 laplaceAbsuchen.f90 DreiecksformPivotisierung.f90 main2.f90 -o Beleg2.exe
----

Damit das Programm nicht abstürtzt muss die richtige `matrix.txt` mit im Ordner sein.

Alle Dateien die eingelesen werden entsprechen folgendem Format

[source]
----
n
1 2 . n
2 3 . .
. . . .
n . . .
----

`n` entspricht der Größe der nachfolgenden **quadratischen** Matrix

== Dateierläuterung

.Übersicht über alle Dateien
[cols="1,4"]
|===
| Dateiname
| Funktion

| `main.f90`
| Hier wird die `matrix.txt` eingelesen und die Subroutinen werden aufgerufen.

| `laplaceNaiv.f90`
| Hier wird der naive Laplace Algorithmus implementiert, welcher immer nach der ersten Spalte entwickelt.

| `laplaceAbsuchen.f90`
| Hier wird der Laplace Algorithmus implementiert, welcher immer nach Spalte oder Zeile mit den meisten Nullen entwickelt.

| `Dreiecksform.f90`
| Hier wird der Algorithmus zur Berechnung der Determinante aus der Vorlesung implementiert.

| `hilfsfunktionen.f90`
| Hier sind alle Hilfsfunktionen, die in mehreren Algorithmen verwendet werden, implementiert.

| `performance.f90`
| Hier ist der Algorithmus zum Errechnen der Performance Zeiten implementiert.

| `matrix_.txt`
| Dies sind Testmatrizen zum Testen des Codes.
|===

== Visualisierung

Es wird angenommen, dass eine TeX Distribution auf dem `PATH` erreichbar ist. Der Befehl für das Auswertdokument ist

.Befehl für den LaTeX
[source,bash]
----
texify builder
texify -p --tex-option="-interaction=nonstopmode" --engine=pdftex --tex-option="--synctex=1" "auswertung.tex"
----

== Todo

- [*] Aufgabe 1: Laplace implementieren
- [*] Aufgabe 2: Entwicklung nach der Spalte mit den meisten Nullelementen
- [*] Aufgabe 3: Pivotisierung und Laufzeitdatenerhebung bei unterschiedlichen Algorithmen
- [*] Aufgabe 4: Automatische Visualisierung der Ergebnisse
